title: Brandon Albers - Data, Business, and Operations Analyst Portfolio
description: A showcase of my skills and projects in data analysis and business operations.

# Use the Hyde theme from GitHub
theme: jekyll-theme-hyde

url: "https://albers1991.github.io"  # The base URL for the site
baseurl: "/Data-Driven-Insights-Business-Operations-Analysis-Portfolio"  # The relative base URL for the repository

markdown: kramdown

plugins:
  - jekyll-include-cache

# Defines where Jekyll looks for CSS and/or JS files
assets:
  css:
    - "assets/css/main.css"