title: Brandon Albers - Data, Business, and Operations Analyst Portfolio
description: A showcase of my skills and projects in data analysis and business operations.
theme: minima

url: "https://username.github.io"  # Replace 'username' with your actual GitHub username
baseurl: ""  # Set to '/repository' if you're using a subdirectory

# Build settings
markdown: kramdown
